# Generated by Django 5.0.6 on 2026-04-18 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['usuario_escuela__usuario__last_name', 'usuario_escuela__usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año Académico',
                'verbose_name_plural': 'Años Académicos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('codigo_acceso', models.CharField(max_length=20, unique=True)),
                ('permite_publicaciones', models.BooleanField(default=True)),
                ('permite_tareas', models.BooleanField(default=True)),
                ('permite_recursos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aula Virtual',
                'verbose_name_plural': 'Aulas Virtuales',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10, verbose_name='División (A, B, C...)')),
                ('turno', models.CharField(choices=[('MANIANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('COMPLETO', 'Jornada Completa')], max_length=20, verbose_name='Turno')),
                ('ciclo', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario')], max_length=20, verbose_name='Ciclo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('anio_creacion', models.PositiveIntegerField(default=2026, verbose_name='Año de creación')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['anio__numero', 'division'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(blank=True, max_length=50, verbose_name='Nombre corto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden en el planilla')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AVISO', 'Aviso/Anuncio'), ('TAREA', 'Tarea'), ('RECURSO', 'Recurso/Material'), ('PREGUNTA', 'Pregunta')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('adjuntos', models.JSONField(blank=True, default=list, verbose_name='Adjuntos (urls)')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
