# Generated by Django 5.0.6 on 2026-04-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usuario_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='users.userschool'),
        ),
        migrations.AddField(
            model_name='anio',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anios', to='schools.school'),
        ),
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academics.anio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='academics.curso'),
        ),
        migrations.AddField(
            model_name='materia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academics.curso'),
        ),
        migrations.AddField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_dictadas', to='users.userschool'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='academics.materia'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='users.userschool'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='academics.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='anio',
            unique_together={('numero', 'escuela')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('anio', 'division')},
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together={('usuario_escuela', 'curso')},
        ),
    ]
