# Generated by Django 5.0.6 on 2026-04-20 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curso_unique_together'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EscalaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_desaprobado', models.PositiveIntegerField(default=6, verbose_name='Límite desaprobado (notas menores a este valor son desaprobadas)')),
                ('escala_json', models.JSONField(blank=True, default=dict, verbose_name='Escala personalizada (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escala_evaluacion', to='schools.school')),
            ],
            options={
                'verbose_name': 'Escala de Evaluación',
                'verbose_name_plural': 'Escalas de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(default=2026, verbose_name='Año académico')),
                ('numero', models.PositiveIntegerField(verbose_name='Número (1, 2, 3...)')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre (ej: 1er Trimestre)')),
                ('fecha_inicio_notas', models.DateField(verbose_name='Fecha inicio carga de notas')),
                ('fecha_fin_notas', models.DateField(verbose_name='Fecha fin carga de notas')),
                ('fecha_inicio_boletin', models.DateField(blank=True, null=True, verbose_name='Fecha inicio boletin')),
                ('fecha_fin_boletin', models.DateField(blank=True, null=True, verbose_name='Fecha fin boletin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='schools.school')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-anio', 'numero'],
                'unique_together': {('escuela', 'anio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ausencias', models.PositiveIntegerField(default=0, verbose_name='Ausencias')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academics.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academics.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academics.periodo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('periodo', 'materia', 'alumno')},
            },
        ),
    ]
