# Generated by Django 5.0.6 on 2026-04-20 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_publicacion_fecha_publicacion_escalaevaluacion_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horarios', to='schools.school')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'ordering': ['orden', 'hora_inicio'],
                'unique_together': {('escuela', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], verbose_name='Día de la semana')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academics.bloquehorario')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='academics.classroom', verbose_name='Aula/Classroom')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academics.curso')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'bloque__orden'],
                'unique_together': {('curso', 'dia_semana', 'bloque')},
            },
        ),
    ]
