# Generated by Django 5.0.6 on 2026-04-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_bloquehorario_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='classroom',
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='academics.materia', verbose_name='Materia'),
        ),
    ]
