# Generated by Django 5.0.6 on 2026-04-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_horario_classroom_horario_materia'),
        ('users', '0002_user_dni_user_localidad_user_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('EXAMEN', 'Examen'), ('TRABAJO', 'Trabajo Práctico'), ('TAREA', 'Tarea')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academics.classroom')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to='users.userschool')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('texto', models.TextField(blank=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota')),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academics.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='users.userschool')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'unique_together': {('actividad', 'alumno')},
            },
        ),
    ]
