# Generated by Django 5.0.6 on 2026-04-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_actividad_entrega'),
        ('schools', '0001_initial'),
        ('users', '0005_add_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avisos/', verbose_name='Imagen adjunta (opcional)')),
                ('importante', models.BooleanField(default=False, verbose_name='Marcar como importante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_creados', to='users.userschool', verbose_name='Autor/Directivo')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='schools.school', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
