# Generated by Django 5.0.6 on 2026-04-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dni_user_localidad_user_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschool',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorados', to='users.userschool', verbose_name='Apoderado/Tutor'),
        ),
    ]
