# Generated by Django 5.0.6 on 2026-04-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userschool_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschool',
            name='codigo_vinculacion',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de Vinculación'),
        ),
    ]
