# Generated by Django 5.0.6 on 2026-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userschool_codigo_vinculacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschool',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
