# Generated by Django 5.0.6 on 2026-04-18 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la escuela')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('cue', models.CharField(blank=True, max_length=20, verbose_name='CUE (Código Único de Establecimiento)')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('habilita_boletin_pdf', models.BooleanField(default=False, verbose_name='Habilitar boletín PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'ordering': ['nombre'],
            },
        ),
    ]
